version: '3.3'

services:
  app:
    image: node:8.12.0-alpine
    container_name: app
    networks:
      eth0:
        ipv4_address: 10.1.1.1
    ports:
      - 3000:3000
      - 4000:4000
      - 9229:9229
    volumes:
      - ./:/var/www/app/
    working_dir: /var/www/app
    command: ['/bin/sh', '-l', '-c', 'npm i && npm start']
    links:
      - mongodb

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    networks:
      eth0:
        ipv4_address: 10.1.1.2
    ports:
      - 27017:27017

networks:
  eth0:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/8
